[CmdletBinding()]
param(
    [string]$DecompilerOutputRoot = 'D:\develop\src\Bannerlord.Binaries',
    [string]$BannerlordRoot = 'C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord',
    [string[]]$Assemblies,
    [switch]$InstallTool
)

$ErrorActionPreference = 'Stop'

function Get-IlspyCmdCommand {
    $command = Get-Command ilspycmd -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    if (-not $InstallTool) {
        throw 'ilspycmd is not installed. Re-run with -InstallTool, or install it first with "dotnet tool install --global ilspycmd".'
    }

    Write-Host 'Installing ilspycmd as a global .NET tool...'
    dotnet tool install --global ilspycmd
    $env:PATH += ';' + (Join-Path $env:USERPROFILE '.dotnet\tools')

    $command = Get-Command ilspycmd -ErrorAction SilentlyContinue
    if (-not $command) {
        throw 'ilspycmd installation completed, but the command is still unavailable in PATH.'
    }

    return $command.Source
}

function Get-GameVersion {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BannerlordRoot
    )

    $nativeSubModulePath = Join-Path $BannerlordRoot 'Modules\Native\SubModule.xml'
    if (-not (Test-Path $nativeSubModulePath)) {
        throw "Could not find Native SubModule.xml: $nativeSubModulePath"
    }

    [xml]$xml = Get-Content $nativeSubModulePath
    $version = $xml.Module.Version.value
    if ([string]::IsNullOrWhiteSpace($version)) {
        throw "Could not read game version from: $nativeSubModulePath"
    }

    return $version
}

function Get-NormalizedVersion {
    param(
        [Parameter(Mandatory = $true)]
        [string]$GameVersion
    )

    $match = [regex]::Match($GameVersion, '^v?(?<version>\d+(?:\.\d+){0,3})$')
    if (-not $match.Success) {
        throw "Unsupported game version format: $GameVersion"
    }

    return [version]$match.Groups['version'].Value
}

function Get-AssemblyMap {
    return [ordered]@{
        'TaleWorlds.CampaignSystem.ViewModelCollection' = 'bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.ViewModelCollection.dll'
        'TaleWorlds.Core'                  = 'bin\Win64_Shipping_Client\TaleWorlds.Core.dll'
        'TaleWorlds.Core.ViewModelCollection' = 'bin\Win64_Shipping_Client\TaleWorlds.Core.ViewModelCollection.dll'
        'TaleWorlds.Diamond'               = 'bin\Win64_Shipping_Client\TaleWorlds.Diamond.dll'
        'TaleWorlds.DotNet'                = 'bin\Win64_Shipping_Client\TaleWorlds.DotNet.dll'
        'TaleWorlds.DotNet.AutoGenerated'  = 'bin\Win64_Shipping_Client\TaleWorlds.DotNet.AutoGenerated.dll'
        'TaleWorlds.Engine'                = 'bin\Win64_Shipping_Client\TaleWorlds.Engine.dll'
        'TaleWorlds.Engine.AutoGenerated'  = 'bin\Win64_Shipping_Client\TaleWorlds.Engine.AutoGenerated.dll'
        'TaleWorlds.Engine.GauntletUI'     = 'bin\Win64_Shipping_Client\TaleWorlds.Engine.GauntletUI.dll'
        'TaleWorlds.GauntletUI'            = 'bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.dll'
        'TaleWorlds.GauntletUI.Data'       = 'bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.Data.dll'
        'TaleWorlds.GauntletUI.ExtraWidgets' = 'bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.ExtraWidgets.dll'
        'TaleWorlds.GauntletUI.PrefabSystem' = 'bin\Win64_Shipping_Client\TaleWorlds.GauntletUI.PrefabSystem.dll'
        'TaleWorlds.InputSystem'           = 'bin\Win64_Shipping_Client\TaleWorlds.InputSystem.dll'
        'TaleWorlds.MountAndBlade'         = 'bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll'
        'TaleWorlds.Localization'          = 'bin\Win64_Shipping_Client\TaleWorlds.Localization.dll'
        'TaleWorlds.CampaignSystem'        = 'bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll'
        'TaleWorlds.Library'              = 'bin\Win64_Shipping_Client\TaleWorlds.Library.dll'
        'TaleWorlds.ModuleManager'         = 'bin\Win64_Shipping_Client\TaleWorlds.ModuleManager.dll'
        'TaleWorlds.MountAndBlade.AutoGenerated' = 'bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.AutoGenerated.dll'
        'TaleWorlds.MountAndBlade.Diamond' = 'bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Diamond.dll'
        'TaleWorlds.MountAndBlade.GauntletUI' = 'Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.GauntletUI.dll'
        'TaleWorlds.MountAndBlade.GauntletUI.Widgets' = 'bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.GauntletUI.Widgets.dll'
        'TaleWorlds.MountAndBlade.Helpers' = 'bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.Helpers.dll'
        'TaleWorlds.MountAndBlade.View'    = 'Modules\Native\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.View.dll'
        'TaleWorlds.MountAndBlade.ViewModelCollection' = 'bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.ViewModelCollection.dll'
        'TaleWorlds.NavigationSystem'      = 'bin\Win64_Shipping_Client\TaleWorlds.NavigationSystem.dll'
        'TaleWorlds.ObjectSystem'          = 'bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll'
        'TaleWorlds.ScreenSystem'          = 'bin\Win64_Shipping_Client\TaleWorlds.ScreenSystem.dll'
        'TaleWorlds.TwoDimension'          = 'bin\Win64_Shipping_Client\TaleWorlds.TwoDimension.dll'
        'SandBox'                         = 'Modules\SandBox\bin\Win64_Shipping_Client\SandBox.dll'
        'SandBox.GauntletUI'              = 'Modules\SandBox\bin\Win64_Shipping_Client\SandBox.GauntletUI.dll'
        'SandBox.View'                    = 'Modules\SandBox\bin\Win64_Shipping_Client\SandBox.View.dll'
        'SandBox.ViewModelCollection'     = 'Modules\SandBox\bin\Win64_Shipping_Client\SandBox.ViewModelCollection.dll'
        'StoryMode'                       = 'Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.dll'
        'StoryMode.View'                  = 'Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.View.dll'
        'StoryMode.ViewModelCollection'   = 'Modules\StoryMode\bin\Win64_Shipping_Client\StoryMode.ViewModelCollection.dll'
        'NavalDLC'                        = 'Modules\NavalDLC\bin\Win64_Shipping_Client\NavalDLC.dll'
        'NavalDLC.View'                   = 'Modules\NavalDLC\bin\Win64_Shipping_Client\NavalDLC.View.dll'
        'NavalDLC.ViewModelCollection'    = 'Modules\NavalDLC\bin\Win64_Shipping_Client\NavalDLC.ViewModelCollection.dll'
        'NavalDLC.GauntletUI'             = 'Modules\NavalDLC\bin\Win64_Shipping_Client\NavalDLC.GauntletUI.dll'
    }
}

if (-not (Test-Path $BannerlordRoot)) {
    throw "Bannerlord root does not exist: $BannerlordRoot"
}

$ilspycmd = Get-IlspyCmdCommand
$assemblyMap = Get-AssemblyMap
$gameVersion = Get-GameVersion -BannerlordRoot $BannerlordRoot
$normalizedGameVersion = Get-NormalizedVersion -GameVersion $gameVersion
$Assemblies = if ($Assemblies -and $Assemblies.Count -gt 0) { $Assemblies } else { @($assemblyMap.Keys) }

if ($normalizedGameVersion -lt [version]'1.3') {
    $navalDlcAssemblies = @($Assemblies | Where-Object { $_ -like 'NavalDLC*' })
    if ($navalDlcAssemblies.Count -gt 0) {
        Write-Warning "Skipping NavalDLC assemblies for $gameVersion because NavalDLC is only available in v1.3 and later."
        $Assemblies = @($Assemblies | Where-Object { $_ -notlike 'NavalDLC*' })
    }
}

$decompilerOutput = Join-Path $DecompilerOutputRoot $gameVersion

New-Item -ItemType Directory -Force -Path $decompilerOutput | Out-Null

foreach ($assemblyName in $Assemblies) {
    if (-not $assemblyMap.Contains($assemblyName)) {
        throw "Unknown assembly key: $assemblyName"
    }

    $dllPath = Join-Path $BannerlordRoot $assemblyMap[$assemblyName]
    if (-not (Test-Path $dllPath)) {
        Write-Warning "Skipping missing assembly: $dllPath"
        continue
    }

    $outputPath = Join-Path $decompilerOutput $assemblyName
    New-Item -ItemType Directory -Force -Path $outputPath | Out-Null

    Write-Host "Decompiling $assemblyName..."
    & $ilspycmd -p -o $outputPath $dllPath
}

Write-Host "Detected game version: $gameVersion"
Write-Host "Done. Decompiled output: $decompilerOutput"
